/*--*- C -*------------------------------------------------------------------*\
**$Author: saulius $
**$Date: 2009-01-12 16:00:09 +0200 (Mon, 12 Jan 2009) $ 
**$Revision: 1335 $
**$URL: svn+ssh2225://vartai.ibt.lt/home/saulius/svn-repositories/compilers/sl/ifunctions/float.cin $
\*---------------------------------------------------------------------------*/

#ifdef I
#undef I
#endif

#define I num.@field@

int @PREFIX@POW( INSTRUCTION_FN_ARGS )
{
    TRACE_FUNCTION();

    istate.ep[1].I = powl( istate.ep[1].I, istate.ep[0].I );
    istate.ep ++;

    return 1;
}
