s/@type@/short/g;
s/@type_min@/SHRT_MIN/g;
s/@type_max@/SHRT_MAX/g;
s/@PREFIX@/H/g;
s/@PREFIX1@/H/g;
s/@field@/s/g;
s/@codeval@/lval/g;
s/@format@/d/g;
s/@printformat@/d/g;
s/@strtobin@/atoi/g;
s/@cval_star@//g
