
.PHONY: all test tests alltests listdiff
.PHONY: bench benchmark benchmarks
.PHONY: clean cleanAll distclean

all:

clean cleanAll distclean:
	rm -f *.o
	rm -f .*.d

test tests alltests bench benchmark benchmarks listdiff : # do nothing
	@true
