s/@type@/int/g;
s/@type_min@/INT_MIN/g;
s/@type_max@/INT_MAX/g;
s/@PREFIX@/I/g;
s/@PREFIX1@//g;
s/@field@/i/g;
s/@codeval@/ssizeval/g;
s/@format@/d/g;
s/@printformat@/d/g;
s/@strtobin@/atoi/g;
s/@cval_star@//g
