s/@type@/llong/g;
s/@type_min@/LLONG_MIN/g;
s/@type_max@/LLONG_MAX/g;
s/@PREFIX@/LL/g;
s/@PREFIX1@/LL/g;
s/@field@/ll/g;
s/@codeval@/llptr/g;
s/@format@/lld/g;
s/@printformat@/lld/g;
s/@strtobin@/atoll/g;
s/@cval_star@/*/g
